name: üê≥ Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - src/**
      - api/**
      - public/**
      - Dockerfile

env:
  IMAGE_NAME: web-check
  DOCKER_USER: lissy93
  GHCR_REGISTRY: ghcr.io
  DOCKERHUB_REGISTRY: docker.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v4

      - name: Extract tag name üè∑Ô∏è
        shell: bash
        run: echo "GIT_TAG=$(echo ${GITHUB_REF#refs/tags/} | sed 's/\//_/g')" >> $GITHUB_ENV

      - name: Compute tags üîñ
        id: compute-tags
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "GHCR_TAG=${GHCR_REGISTRY}/${DOCKER_USER}/${IMAGE_NAME}:latest" >> $GITHUB_ENV
            echo "DOCKERHUB_TAG=${DOCKERHUB_REGISTRY}/${DOCKER_USER}/${IMAGE_NAME}:latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "GHCR_TAG=${GHCR_REGISTRY}/${DOCKER_USER}/${IMAGE_NAME}:${GIT_TAG}" >> $GITHUB_ENV
            echo "DOCKERHUB_TAG=${DOCKERHUB_REGISTRY}/${DOCKER_USER}/${IMAGE_NAME}:${GIT_TAG}" >> $GITHUB_ENV
          fi

      - name: Set up QEMU üêß
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx üê≥
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry üîë
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub üîë
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKERHUB_REGISTRY }}
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images üõ†Ô∏è
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            ${{ env.GHCR_TAG }}
            ${{ env.DOCKERHUB_TAG }}

      - name: üóÇÔ∏è Make Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.DOCKERHUB_REGISTRY }}/${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}
            ${{ env.GHCR_REGISTRY }}/${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}},enable=true
            type=semver,pattern={{major}}.x
            type=raw,value=latest
          flavor: |
            latest=false
          labels: |
            maintainer=Lissy93
            org.opencontainers.image.title=Web Check
            org.opencontainers.image.description=Xray Vision for any Website
            org.opencontainers.image.documentation=https://web-check.xyz
            org.opencontainers.image.authors=Alicia Sykes
            org.opencontainers.image.licenses=MIT
